// ==============================================================================
// AUTOMATICALLY GENERATED BY AQIL v12 FLEET PIPELINE GENERATOR
// Single source of truth: D:/Program/Antigravity/aqil_core_v10
// Tests all discovered screens across 5 viewports, 3 font scales, and theme matrix.
// ==============================================================================

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:aqil_core/aqil_core.dart';
import 'package:todo_app/ui/views/auth/login_screen.dart';
import 'package:todo_app/ui/views/auth/register_screen.dart';
import 'package:todo_app/ui/views/profile/profile_screen.dart';
import 'package:todo_app/ui/views/todos/todo_detail_screen.dart';
import 'package:todo_app/ui/views/todos/todo_home_screen.dart';


void main() {
  group('AQIL Universal Automated Screen Pipeline [5 Screens]', () {
    testAqilScreen(
      'LoginScreen renders with zero layout overflow across all viewports',
      builder: (context) => Scaffold(
        body: const LoginScreen(),
      ),
    );

    testAqilScreen(
      'RegisterScreen renders with zero layout overflow across all viewports',
      builder: (context) => Scaffold(
        body: const RegisterScreen(),
      ),
    );

    testAqilScreen(
      'ProfileScreen renders with zero layout overflow across all viewports',
      builder: (context) => Scaffold(
        body: const ProfileScreen(),
      ),
    );

    testAqilScreen(
      'TodoDetailScreen renders with zero layout overflow across all viewports',
      builder: (context) => Scaffold(
        body: const TodoDetailScreen(),
      ),
    );

    testAqilScreen(
      'TodoHomeScreen renders with zero layout overflow across all viewports',
      builder: (context) => Scaffold(
        body: const TodoHomeScreen(),
      ),
    );


  });
}
